name: weather_repository
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  coverage: ^1.7.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.24.9

flutter:
